import React from 'react';
import { AbsoluteFill, Series, useCurrentFrame, interpolate } from 'remotion';
import { RealTweetEvidence } from '../../components/RealTweetEvidence';
import {
  Gamepad2,
  Code2,
  Cpu,
  Layers,
  Sparkles,
  Zap,
  Activity,
  CheckCircle2,
  Terminal,
  Play,
  Volume2,
  Maximize2,
} from 'lucide-react';

export const Act2BenchmarkCarnage: React.FC = () => {
  return (
    <AbsoluteFill style={{ backgroundColor: '#05070E' }}>
      <Series>
        {/* Micro-beat 6: 0-540 (18.0s) -> The Pelican Torture Test */}
        <Series.Sequence durationInFrames={540}>
          <Beat6PelicanTortureTest />
        </Series.Sequence>

        {/* Micro-beat 7: 540-1080 (18.0s) -> SVG Vector Code Inspection */}
        <Series.Sequence durationInFrames={540}>
          <Beat7SvgCodeInspection />
        </Series.Sequence>

        {/* Micro-beat 8: 1080-1630 (18.3s) -> EVIDENCE TWEET 2: @SahilPanhotra Animated Peacock */}
        <Series.Sequence durationInFrames={550}>
          <RealTweetEvidence
            imageFile="sahil_peacock_tweet.png"
            authorName="Sahil Panhotra"
            handle="SahilPanhotra"
            categoryTag="ANIMATED SVG BENCHMARK"
            highlightText="make an animated SVG of a peacock riding a bike... if this really is Gemini 4 Pro, Google has been cooking"
            statValue="100% KINETIC"
            statLabel="VECTOR DYNAMICS"
            keyInsight="Calculated procedural vector physics rather than static SVG paths."
          />
        </Series.Sequence>

        {/* Micro-beat 9: 1630-2180 (18.3s) -> The 1-Shot Undertale Sandbox */}
        <Series.Sequence durationInFrames={550}>
          <Beat9UndertaleSandbox />
        </Series.Sequence>

        {/* Micro-beat 10: 2180-2742 (18.7s) -> EVIDENCE TWEET 3: @mirochill Undertale 1-Shot Leak */}
        <Series.Sequence durationInFrames={562}>
          <RealTweetEvidence
            imageFile="mirochill_undertale_tweet.png"
            authorName="Mirochill"
            handle="mirochill"
            categoryTag="1-SHOT GAME SYNTHESIS"
            highlightText="Leak of Gemini 4 Pro on the game Undertale. All the assets as well as the audio were generated by the model in one shot"
            statValue="1-SHOT"
            statLabel="FULL GAME & AUDIO"
            keyInsight="Complete playable browser game with synthesized audio and functional combat logic."
          />
        </Series.Sequence>
      </Series>
    </AbsoluteFill>
  );
};

// --- BEAT 6: THE PELICAN TORTURE TEST ---
const Beat6PelicanTortureTest: React.FC = () => {
  return (
    <div style={{ width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '36px 60px', boxSizing: 'border-box' }}>
      <div style={{ width: 1760, height: 820, backgroundColor: '#070B14', border: '1px solid rgba(255,255,255,0.15)', borderRadius: 24, padding: '40px', boxSizing: 'border-box', display: 'flex', flexDirection: 'column', gap: 24 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <div style={{ color: '#F59E0B', fontSize: 14, fontWeight: 800, letterSpacing: 3 }}>GEOMETRIC REASONING TORTURE TEST</div>
            <div style={{ color: '#FFFFFF', fontSize: 36, fontWeight: 900, marginTop: 6 }}>
              "Pelican Riding a Bicycle" // Zero-Shot SVG Shootout
            </div>
          </div>
          <div style={{ padding: '8px 18px', borderRadius: 8, backgroundColor: 'rgba(245,158,11,0.15)', color: '#FBBF24', fontSize: 14, fontWeight: 700 }}>
            BENCHMARK: VECTOR PATH FIDELITY
          </div>
        </div>

        {/* Side-by-side shootout containers */}
        <div style={{ flex: 1, display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 24 }}>
          {/* Flash Standard */}
          <div style={{ backgroundColor: 'rgba(15,23,42,0.6)', borderRadius: 16, border: '1px solid rgba(239,68,68,0.3)', padding: 24, display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
            <div>
              <div style={{ color: '#EF4444', fontSize: 13, fontWeight: 800 }}>BASELINE FLASH</div>
              <div style={{ color: '#FFFFFF', fontSize: 24, fontWeight: 800, marginTop: 4 }}>Standard 3.8 Flash</div>
              <p style={{ color: '#94A3B8', fontSize: 15, marginTop: 12 }}>
                Collapsed paths. Crossed lines. Spoke geometry disconnected from hub. Anatomy unidentifiable.
              </p>
            </div>
            <div style={{ padding: '12px 16px', borderRadius: 8, backgroundColor: 'rgba(239,68,68,0.1)', color: '#EF4444', fontWeight: 700, fontSize: 14, textAlign: 'center' }}>
              RESULT: PATH COLLAPSE
            </div>
          </div>

          {/* Gemini 4 Pro */}
          <div style={{ backgroundColor: 'rgba(30,58,138,0.3)', borderRadius: 16, border: '2px solid #38BDF8', padding: 24, display: 'flex', flexDirection: 'column', justifyContent: 'space-between', boxShadow: '0 0 35px rgba(56,189,248,0.2)' }}>
            <div>
              <div style={{ color: '#38BDF8', fontSize: 13, fontWeight: 800 }}>UNMASKED ARGON-D</div>
              <div style={{ color: '#FFFFFF', fontSize: 24, fontWeight: 900, marginTop: 4 }}>Gemini 4 Pro</div>
              <p style={{ color: '#93C5FD', fontSize: 15, marginTop: 12 }}>
                Full semantic grouping. Individual 36-spoke wheels with correct tension. Pelican bill and pedal crank connected.
              </p>
            </div>
            <div style={{ padding: '12px 16px', borderRadius: 8, backgroundColor: 'rgba(56,189,248,0.2)', color: '#38BDF8', fontWeight: 800, fontSize: 14, textAlign: 'center' }}>
              RESULT: FLAWLESS SEMANTIC VECTORS
            </div>
          </div>

          {/* GPT-6 Astra */}
          <div style={{ backgroundColor: 'rgba(15,23,42,0.6)', borderRadius: 16, border: '1px solid rgba(16,185,129,0.4)', padding: 24, display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
            <div>
              <div style={{ color: '#10A37F', fontSize: 13, fontWeight: 800 }}>OPENAI FLAGSHIP</div>
              <div style={{ color: '#FFFFFF', fontSize: 24, fontWeight: 800, marginTop: 4 }}>GPT-6 Astra Pro</div>
              <p style={{ color: '#94A3B8', fontSize: 15, marginTop: 12 }}>
                Near-identical vector grouping. High artistic shading. Parity confirmed by @LuminaBench.
              </p>
            </div>
            <div style={{ padding: '12px 16px', borderRadius: 8, backgroundColor: 'rgba(16,185,129,0.15)', color: '#10A37F', fontWeight: 700, fontSize: 14, textAlign: 'center' }}>
              RESULT: DEAD HEAT PARITY
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

// --- BEAT 7: SVG CODE INSPECTION ---
const Beat7SvgCodeInspection: React.FC = () => {
  return (
    <div style={{ width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '36px 60px', boxSizing: 'border-box' }}>
      <div style={{ width: 1760, height: 820, backgroundColor: '#070B14', border: '1px solid rgba(96,165,250,0.3)', borderRadius: 24, padding: '44px 56px', boxSizing: 'border-box', display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
            <Code2 size={24} color="#38BDF8" />
            <span style={{ color: '#38BDF8', fontSize: 18, fontWeight: 800, fontFamily: 'monospace' }}>DECOMPILED SVG SOURCE // CODE FORENSICS</span>
          </div>
          <span style={{ color: '#22C55E', fontFamily: 'monospace', fontSize: 15 }}>NESTED BEZIER PRECISION</span>
        </div>

        {/* Code Diff Display */}
        <div style={{ backgroundColor: '#000000', borderRadius: 16, border: '1px solid rgba(255,255,255,0.1)', padding: 32, fontFamily: 'monospace', fontSize: 18, color: '#E2E8F0', lineHeight: 1.6 }}>
          <div style={{ color: '#64748B' }}>&lt;!-- Gemini 4 Pro argon-d Generated SVG Hierarchy --&gt;</div>
          <div style={{ color: '#38BDF8', marginTop: 8 }}>&lt;svg viewBox="0 0 1920 1080" xmlns="http://www.w3.org/2000/svg"&gt;</div>
          <div style={{ paddingLeft: 24, color: '#F59E0B' }}>&lt;g id="pelican-body" transform="matrix(1.02, 0, 0, 1.02, 450, 280)"&gt;</div>
          <div style={{ paddingLeft: 48, color: '#94A3B8' }}>&lt;path d="M 120 45 C 180 20, 240 70, 310 95 C 380 120, 420 80, 490 60 ..." fill="url(#featherGradient)" /&gt;</div>
          <div style={{ paddingLeft: 24, color: '#F59E0B' }}>&lt;/g&gt;</div>
          <div style={{ paddingLeft: 24, color: '#22C55E', marginTop: 8 }}>&lt;g id="wheel-spokes-radial" stroke="#E2E8F0" stroke-width="1.5"&gt;</div>
          <div style={{ paddingLeft: 48, color: '#A7F3D0' }}>&lt;line x1="300" y1="600" x2="420" y2="720" /&gt; &lt;!-- Procedural 36-spoke hub anchor --&gt;</div>
          <div style={{ paddingLeft: 24, color: '#22C55E' }}>&lt;/g&gt;</div>
          <div style={{ color: '#38BDF8', marginTop: 8 }}>&lt;/svg&gt;</div>
        </div>

        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <span style={{ color: '#94A3B8', fontSize: 16 }}>RESOLUTION SCALING: <strong style={{ color: '#FFFFFF' }}>INFINITE VECTOR FIDELITY (8K DISPLAY VERIFIED)</strong></span>
          <span style={{ color: '#38BDF8', fontSize: 16, fontWeight: 700 }}>ZERO-SHOT CODE GENERATION SPEED: <strong>~6.2 SECONDS</strong></span>
        </div>
      </div>
    </div>
  );
};

// --- BEAT 9: THE 1-SHOT UNDERTALE SANDBOX ---
const Beat9UndertaleSandbox: React.FC = () => {
  return (
    <div style={{ width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '36px 60px', boxSizing: 'border-box' }}>
      <div style={{ width: 1760, height: 820, backgroundColor: '#070B14', border: '1px solid rgba(239,68,68,0.4)', borderRadius: 24, padding: '40px', boxSizing: 'border-box', display: 'flex', flexDirection: 'column', gap: 24, boxShadow: '0 25px 60px -15px rgba(239,68,68,0.2)' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
            <Gamepad2 size={26} color="#EF4444" />
            <span style={{ color: '#FFFFFF', fontSize: 26, fontWeight: 800 }}>END-TO-END GAME COMPILATION // "UNDERTALE" 1-SHOT</span>
          </div>
          <div style={{ padding: '6px 16px', borderRadius: 8, backgroundColor: 'rgba(239,68,68,0.2)', color: '#EF4444', fontSize: 14, fontWeight: 800, letterSpacing: 2 }}>
            LEAK DISCLOSURE: @MIROCHILL
          </div>
        </div>

        {/* Dual Pane Game Sandbox */}
        <div style={{ flex: 1, display: 'grid', gridTemplateColumns: '1.2fr 0.8fr', gap: 32 }}>
          {/* Left: Playable Canvas Window */}
          <div style={{ backgroundColor: '#000000', borderRadius: 16, border: '2px solid rgba(255,255,255,0.2)', padding: 24, display: 'flex', flexDirection: 'column', justifyContent: 'space-between', position: 'relative' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid rgba(255,255,255,0.1)', paddingBottom: 12 }}>
              <span style={{ color: '#FFFFFF', fontSize: 16, fontFamily: 'monospace' }}>CANVAS: UNDER_TALE_ARENA.HTML</span>
              <span style={{ color: '#22C55E', fontSize: 14, fontFamily: 'monospace' }}>60 FPS // RUNNING</span>
            </div>

            {/* Simulated Retro Pixel Art Combat Box */}
            <div style={{ flex: 1, margin: '20px 0', border: '3px solid #FFFFFF', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', backgroundColor: '#05070E' }}>
              <div style={{ color: '#FFFFFF', fontSize: 28, fontFamily: 'monospace', fontWeight: 900 }}>[ * SANS APPEARED. ]</div>
              <div style={{ width: 24, height: 24, backgroundColor: '#EF4444', marginTop: 32, transform: 'rotate(45deg)' }} />
              <div style={{ color: '#94A3B8', fontSize: 14, fontFamily: 'monospace', marginTop: 16 }}>SOUL HITBOX // COLLISION ACTIVE</div>
            </div>

            <div style={{ display: 'flex', justifyContent: 'space-between', color: '#64748B', fontSize: 14, fontFamily: 'monospace' }}>
              <span>CONTROLS: ARROWS / Z TO ACT</span>
              <span>AUDIO: REAL-TIME 8-BIT SYNTHESIZER</span>
            </div>
          </div>

          {/* Right: Architectural Telemetry */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
            <div style={{ backgroundColor: 'rgba(15,23,42,0.7)', borderRadius: 14, border: '1px solid rgba(255,255,255,0.1)', padding: 20 }}>
              <div style={{ color: '#64748B', fontSize: 13, textTransform: 'uppercase' }}>EXECUTION MODE</div>
              <div style={{ color: '#FFFFFF', fontSize: 22, fontWeight: 800, marginTop: 4 }}>Single Prompt (1-Shot)</div>
              <p style={{ color: '#94A3B8', fontSize: 14, marginTop: 8 }}>
                No multi-turn scaffolding or external coding agent loops. Generated in one continuous token stream.
              </p>
            </div>

            <div style={{ backgroundColor: 'rgba(15,23,42,0.7)', borderRadius: 14, border: '1px solid rgba(255,255,255,0.1)', padding: 20 }}>
              <div style={{ color: '#64748B', fontSize: 13, textTransform: 'uppercase' }}>AUDIO SYNTHESIS</div>
              <div style={{ color: '#38BDF8', fontSize: 22, fontWeight: 800, marginTop: 4 }}>Web Audio API Oscillator</div>
              <p style={{ color: '#94A3B8', fontSize: 14, marginTop: 8 }}>
                Synthesized sound effects directly via Javascript audio nodes—zero external MP3 assets needed.
              </p>
            </div>

            <div style={{ backgroundColor: 'rgba(239,68,68,0.15)', borderRadius: 14, border: '1px solid #EF4444', padding: 20 }}>
              <div style={{ color: '#EF4444', fontSize: 13, fontWeight: 800, textTransform: 'uppercase' }}>THE SIGNIFICANCE</div>
              <div style={{ color: '#FFFFFF', fontSize: 18, fontWeight: 700, marginTop: 4 }}>Procedural Software Generation</div>
              <p style={{ color: '#CBD5E1', fontSize: 14, marginTop: 8 }}>
                This is not next-token autocomplete. This is full spatial and game-loop reasoning.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
